[package]
name = "cantucci"
version = "0.1.0"
authors = [
    "Lukas Kalbertodt <lukas.kalbertodt@gmail.com>",
    "Julian Kniephoff <me@juliankniephoff.com>",
]

[dependencies]
core = { path = "core/" }
minifb = "0.9"
